export { default as Button } from './Button'
export { default as ButtonText } from './ButtonText'
export { default as ButtonEscolha} from './ButtonEscolha'
export { default as Header} from './Header'
export { default as Foto} from './Foto'
