export { default as Button } from './Button'
export { default as ButtonText } from './ButtonText'
export { default as ButtonEscolha} from './ButtonEscolha'
export { default as ButtonCamera} from './ButtonCamera'
export { default as ButtonGaveta} from './ButtonGaveta'
export { default as ButtonConfig} from './ButtonConfig'
export { default as ButtonFeedback} from './ButtonFeedback'
export { default as ButtonCadastrarFoto} from './ButtonCadastrarFoto'
export { default as ButtonEditar} from './ButtonEditar'
export { default as Foto} from './Foto'
export { default as Header} from './Header'
export { default as Loading} from './Loading'

